### ISSUE TITLE
Game Crash when crafting second requested item (Steam Version)

### ISSUE THREAD

**Issue by Kahrie** [nhydock/Storymode#10]
As it says on the tin.

1. Fresh save file.
2. Enter crafting menu in town
3. Click second item in 'my list' section
4. Click/press "Make Item"
5. Game crash

Picked up _JAVA_OPTIONS: -Xmx2G -Xms2G
Setting breakpad minidump AppID = 386710
Steam_SetMinidumpSteamID:  Caching Steam ID:  [API loaded no]
Dungeon Generation: Building 19 floors
RenderSystem: Map set
```
Exception in thread "LWJGL Application" java.lang.NullPointerException: Craftabl
e object can not be null
        at com.nhydock.storymode.scenes.town.ui.TownState$4.refreshRequirements(
TownState.java:193)
        at com.nhydock.storymode.scenes.town.ui.TownState$4.onMessage(TownState.
java:299)
        at com.nhydock.storymode.scenes.town.ui.TownState$4.onMessage(TownState.
java:168)
        at com.badlogic.gdx.ai.fsm.DefaultStateMachine.handleMessage(DefaultStat
eMachine.java:146)
        at com.nhydock.storymode.scenes.UI.handleMessage(UI.java:305)
        at com.nhydock.storymode.scenes.GameUI.handleMessage(GameUI.java:634)
        at com.nhydock.storymode.scenes.town.ui.TownUI.handleMessage(TownUI.java
:937)
        at com.badlogic.gdx.ai.msg.MessageDispatcher.discharge(MessageDispatcher
.java:400)
        at com.badlogic.gdx.ai.msg.MessageDispatcher.dispatchMessage(MessageDisp
atcher.java:317)
        at com.badlogic.gdx.ai.msg.MessageDispatcher.dispatchMessage(MessageDisp
atcher.java:221)
        at com.nhydock.scenes.scene2d.ui.ScrollOnChange.changed(ScrollOnChange.j
ava:45)
        at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeLis
tener.java:28)
        at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:181)
        at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:146)
        at com.badlogic.gdx.scenes.scene2d.utils.Selection.fireChangeEvent(Selec
tion.java:190)
        at com.badlogic.gdx.scenes.scene2d.utils.Selection.clear(Selection.java:
176)
        at com.badlogic.gdx.scenes.scene2d.utils.ArraySelection.validate(ArraySe
lection.java:56)
        at com.badlogic.gdx.scenes.scene2d.ui.List.setItems(List.java:229)
        at com.nhydock.storymode.scenes.town.ui.TownState$4.populateLoot(TownSta
te.java:180)
        at com.nhydock.storymode.scenes.town.ui.TownState$4.onMessage(TownState.
java:262)
        at com.nhydock.storymode.scenes.town.ui.TownState$4.onMessage(TownState.
java:168)
        at com.badlogic.gdx.ai.fsm.DefaultStateMachine.handleMessage(DefaultStat
eMachine.java:146)
        at com.nhydock.storymode.scenes.UI.handleMessage(UI.java:305)
        at com.nhydock.storymode.scenes.GameUI.handleMessage(GameUI.java:634)
        at com.nhydock.storymode.scenes.town.ui.TownUI.handleMessage(TownUI.java
:937)
        at com.badlogic.gdx.ai.msg.MessageDispatcher.discharge(MessageDispatcher
.java:400)
        at com.badlogic.gdx.ai.msg.MessageDispatcher.dispatchMessage(MessageDisp
atcher.java:317)
        at com.badlogic.gdx.ai.msg.MessageDispatcher.dispatchMessage(MessageDisp
atcher.java:221)
        at com.nhydock.storymode.scenes.GameUI.triggerAction(GameUI.java:388)
        at com.nhydock.storymode.scenes.GameUI$4.touchDown(GameUI.java:106)
        at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.ja
va:56)
        at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:181)
        at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
        at com.badlogic.gdx.scenes.scene2d.Stage.touchDown(Stage.java:277)
        at com.badlogic.gdx.InputMultiplexer.touchDown(InputMultiplexer.java:90)

        at com.nhydock.storymode.service.implementations.InputHandler.touchDown(
InputHandler.java:58)
        at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.j
ava:303)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplic
ation.java:207)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplicati
on.java:120)
```

**Comment by nhydock** [comment]
Thank you for the bug report.  It appeared as though my latest update which reworked items effectively broke crafting and its interface.  I just pushed out an update that should fix the issue in the Steam version.  Update will be rolling out this weekend for the Shareware edition

**Comment by Kahrie** [comment]
Updated client and booted up to confirm- and crashed again in the same place with a similar error.
```
Exception in thread "LWJGL Application" java.lang.NullPointerException: Craftabl
e object can not be null
        at com.nhydock.storymode.scenes.town.ui.TownState$4.refreshRequirements(
TownState.java:198)
        at com.nhydock.storymode.scenes.town.ui.TownState$4.onMessage(TownState.
java:307)
        at com.nhydock.storymode.scenes.town.ui.TownState$4.onMessage(TownState.
java:171)
        at com.badlogic.gdx.ai.fsm.DefaultStateMachine.handleMessage(DefaultStat
eMachine.java:146)
        at com.nhydock.storymode.scenes.UI.handleMessage(UI.java:305)
        at com.nhydock.storymode.scenes.GameUI.handleMessage(GameUI.java:634)
        at com.nhydock.storymode.scenes.town.ui.TownUI.handleMessage(TownUI.java
:937)
        at com.badlogic.gdx.ai.msg.MessageDispatcher.discharge(MessageDispatcher
.java:400)
        at com.badlogic.gdx.ai.msg.MessageDispatcher.dispatchMessage(MessageDisp
atcher.java:317)
        at com.badlogic.gdx.ai.msg.MessageDispatcher.dispatchMessage(MessageDisp
atcher.java:221)
        at com.nhydock.scenes.scene2d.ui.ScrollOnChange.changed(ScrollOnChange.j
ava:45)
        at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeLis
tener.java:28)
        at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:181)
        at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:146)
        at com.badlogic.gdx.scenes.scene2d.utils.Selection.fireChangeEvent(Selec
tion.java:190)
        at com.badlogic.gdx.scenes.scene2d.utils.Selection.clear(Selection.java:
176)
        at com.badlogic.gdx.scenes.scene2d.utils.ArraySelection.validate(ArraySe
lection.java:56)
        at com.badlogic.gdx.scenes.scene2d.ui.List.setItems(List.java:229)
        at com.nhydock.storymode.scenes.town.ui.TownState$4.populateLoot(TownSta
te.java:183)
        at com.nhydock.storymode.scenes.town.ui.TownState$4.onMessage(TownState.
java:270)
        at com.nhydock.storymode.scenes.town.ui.TownState$4.onMessage(TownState.
java:171)
        at com.badlogic.gdx.ai.fsm.DefaultStateMachine.handleMessage(DefaultStat
eMachine.java:146)
        at com.nhydock.storymode.scenes.UI.handleMessage(UI.java:305)
        at com.nhydock.storymode.scenes.GameUI.handleMessage(GameUI.java:634)
        at com.nhydock.storymode.scenes.town.ui.TownUI.handleMessage(TownUI.java
:937)
        at com.badlogic.gdx.ai.msg.MessageDispatcher.discharge(MessageDispatcher
.java:400)
        at com.badlogic.gdx.ai.msg.MessageDispatcher.dispatchMessage(MessageDisp
atcher.java:317)
        at com.badlogic.gdx.ai.msg.MessageDispatcher.dispatchMessage(MessageDisp
atcher.java:221)
        at com.nhydock.storymode.scenes.GameUI.triggerAction(GameUI.java:388)
        at com.nhydock.storymode.scenes.GameUI$4.touchDown(GameUI.java:106)
        at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.ja
va:56)
        at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:181)
        at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:146)
        at com.badlogic.gdx.scenes.scene2d.Stage.touchDown(Stage.java:277)
        at com.badlogic.gdx.InputMultiplexer.touchDown(InputMultiplexer.java:90)

        at com.nhydock.storymode.service.implementations.InputHandler.touchDown(
InputHandler.java:58)
        at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.j
ava:303)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplic
ation.java:207)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplicati
on.java:120)
```

**Comment by nhydock** [comment]
Sorry about the save file causing a crash.  I should probably attach a versioning system to the application that can be used to mark save compatibility issues.  Do to the large rewrite of the item system, save files from before that patch can no longer be used.
