### ISSUE TITLE
Game Crash starting boss encounter. (Steam version)

### ISSUE THREAD

**Issue by Kahrie** [nhydock/Storymode#11]
After bumping into a dangerous encounter/boss enemy, the game crashes immediately after the screen distortion finishes.
(Edit: This was happening in the daily dungeon. Have not encountered a boss inside a regular file yet.)
```
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeExcepti
on: java.lang.NoSuchMethodError: com.badlogic.gdx.scenes.scene2d.utils.TiledDraw
able.setRepeat(ZZ)V
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplicati
on.java:127)
Caused by: java.lang.NoSuchMethodError: com.badlogic.gdx.scenes.scene2d.utils.Ti
ledDrawable.setRepeat(ZZ)V
        at com.nhydock.storymode.scenes.battle.ui.BattleUI.makeField(BattleUI.ja
va:424)
        at com.nhydock.storymode.scenes.battle.ui.BattleUI.extend(BattleUI.java:
225)
        at com.nhydock.storymode.scenes.GameUI.create(GameUI.java:259)
        at com.nhydock.storymode.scenes.battle.Scene.init(Scene.java:46)
        at com.nhydock.storymode.scenes.Scene.render(Scene.java:63)
        at com.nhydock.storymode.Storymode.render(Storymode.java:198)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplic
ation.java:215)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplicati
on.java:120)
```

**Comment by nhydock** [comment]
Dang it, I know exactly what's causing this. I guess I'll just move the class into a new package instead of trying to override it when packaging the jar.  Should fix up the problem.  I'll do this tonight

**Comment by nhydock** [comment]
Patch has been pushed upstream.  Please confirm that the error has been fixed for you.

As this pertains to boss battles, one way to insure you land on a boss floor you can add the -debug argument to the command executed by storymode.sh.  The first floor of any dungeon will then be a boss floor

**Comment by Kahrie** [comment]
Fix confirmed- Boss encounters are now running without any problems. Thank you!
