### ISSUE TITLE
NPE on attempt to enter dungeon

### ISSUE THREAD

**Issue by de-ko** [nhydock/Storymode#18]
I've played through couple of dungeons, saved the game and tried to enter another dungeon.

>001: Labyrinth - PeriTune
002: Lost Place - PeriTune
java.lang.NullPointerException
        at com.nhydock.storymode.scenes.dungeon.MovementSystem.isWall(MovementSystem.java:131)
        at com.nhydock.storymode.scenes.dungeon.MovementSystem.isWall(MovementSystem.java:178)
        at com.nhydock.storymode.scenes.dungeon.MovementSystem.movePlayer(MovementSystem.java:763)
        at com.nhydock.storymode.scenes.dungeon.ui.WanderState$2.onMessage(WanderState.java:115)
        at com.nhydock.storymode.scenes.dungeon.ui.WanderState$2.onMessage(WanderState.java:75)
        at com.badlogic.gdx.ai.fsm.DefaultStateMachine.handleMessage(DefaultStateMachine.java:162)
        at com.nhydock.storymode.scenes.UI.handleMessage(UI.java:378)
        at com.nhydock.storymode.scenes.dungeon.ui.WanderUI.handleMessage(WanderUI.java:794)
        at com.badlogic.gdx.ai.msg.MessageDispatcher.discharge(MessageDispatcher.java:583)
        at com.badlogic.gdx.ai.msg.MessageDispatcher.dispatchMessage(MessageDispatcher.java:490)
        at com.badlogic.gdx.ai.msg.MessageDispatcher.dispatchMessage(MessageDispatcher.java:248)
        at com.nhydock.storymode.scenes.dungeon.ui.WanderState$2.touchDown(WanderState.java:232)
        at com.nhydock.storymode.scenes.dungeon.ui.WanderUI$4.touchDown(WanderUI.java:415)
        at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:56)
        at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:181)
        at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
        at com.badlogic.gdx.scenes.scene2d.Stage.touchDown(Stage.java:282)
        at com.badlogic.gdx.InputMultiplexer.touchDown(InputMultiplexer.java:90)
        at com.nhydock.storymode.service.implementations.InputHandler.touchDown(InputHandler.java:68)
        at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:78)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Input.update(Lwjgl3Input.java:187)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:237)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:122)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:95)
        at com.nhydock.storymode.DesktopLauncher.main(DesktopLauncher.java:40)

**Comment by nhydock** [comment]
Looks like not all of the input events were being processed in the queue before the scene would switch, which would cause the dungeon interface's input handler to execute a movement event before the dungeon was initialized.

Fix will be pushed in a moment.
