### ISSUE TITLE
Game crashes when trying to improve stat that has value of 1

### ISSUE THREAD

**Issue by de-ko** [nhydock/Storymode#21]
My character had a vitality score equal to 1, and when I've tried to increase it at a trainer in a dungeon, the game has crashed. The required price to increase was 0 items.

>com.badlogic.gdx.utils.GdxRuntimeException: The required amount of items to sacrifice must be greater than 0
        at com.nhydock.storymode.datatypes.Inventory.sacrifice(Inventory.java:281)
        at com.nhydock.storymode.scenes.dungeon.ui.WanderState$5.onMessage(WanderState.java:530)
        at com.nhydock.storymode.scenes.dungeon.ui.WanderState$5.onMessage(WanderState.java:508)
        at com.badlogic.gdx.ai.fsm.DefaultStateMachine.handleMessage(DefaultStateMachine.java:162)
        at com.nhydock.storymode.scenes.UI.handleMessage(UI.java:378)
        at com.nhydock.storymode.scenes.dungeon.ui.WanderUI.handleMessage(WanderUI.java:794)
        at com.badlogic.gdx.ai.msg.MessageDispatcher.discharge(MessageDispatcher.java:583)
        at com.badlogic.gdx.ai.msg.MessageDispatcher.dispatchMessage(MessageDispatcher.java:490)
        at com.badlogic.gdx.ai.msg.MessageDispatcher.dispatchMessage(MessageDispatcher.java:212)
        at com.nhydock.storymode.scenes.SacrificeSubmenu$1.touchDown(SacrificeSubmenu.java:99)
        at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:56)
        at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:181)
        at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
        at com.badlogic.gdx.scenes.scene2d.Stage.touchDown(Stage.java:282)
        at com.badlogic.gdx.InputMultiplexer.touchDown(InputMultiplexer.java:90)
        at com.nhydock.storymode.service.implementations.InputHandler.touchDown(InputHandler.java:68)
        at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:78)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Input.update(Lwjgl3Input.java:187)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:237)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:122)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:95)
        at com.nhydock.storymode.DesktopLauncher.main(DesktopLauncher.java:40)

**Comment by nhydock** [comment]
Another ui bug.  Fix will be pushed in a moment.  Trainers now require a minimum of 1 item so this won't happen again.  Interesting that I was smart enough to actually put a relevant exception message for myself when something like this would happen.

Also, creation ui had a bug, so that should be fixed now.  Characters with 1 vitality should have 2 hp, not 1.  As there's no way to detect this condition from the current save file format, any characters made with 1 vitality before this update will always have 1 less hp than they should.
